name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours to keep it fresh
  workflow_dispatch: # Allows you to manually trigger it via the Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Push SVGs to Output Branch
        uses: crazy-max/ghaction-github-pages@v4 # Upgraded to v4 to remove Node deprecation warnings
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
